Compiled from "AsyncErrorServlet.java"
class io.undertow.servlet.test.async.AsyncErrorServlet$1 implements java.lang.Runnable {
  final javax.servlet.http.HttpServletResponse val$resp;

  final io.undertow.servlet.test.async.AsyncErrorServlet this$0;

  io.undertow.servlet.test.async.AsyncErrorServlet$1(io.undertow.servlet.test.async.AsyncErrorServlet, javax.servlet.http.HttpServletResponse);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #1                  // Field this$0:Lio/undertow/servlet/test/async/AsyncErrorServlet;
       5: aload_0
       6: aload_2
       7: putfield      #2                  // Field val$resp:Ljavax/servlet/http/HttpServletResponse;
      10: aload_0
      11: invokespecial #3                  // Method java/lang/Object."<init>":()V
      14: return

  public void run();
    Code:
       0: ldc2_w        #4                  // long 100l
       3: invokestatic  #6                  // Method java/lang/Thread.sleep:(J)V
       6: aload_0
       7: getfield      #2                  // Field val$resp:Ljavax/servlet/http/HttpServletResponse;
      10: sipush        500
      13: invokeinterface #8,  2            // InterfaceMethod javax/servlet/http/HttpServletResponse.sendError:(I)V
      18: goto          31
      21: astore_1
      22: new           #10                 // class java/lang/RuntimeException
      25: dup
      26: aload_1
      27: invokespecial #11                 // Method java/lang/RuntimeException."<init>":(Ljava/lang/Throwable;)V
      30: athrow
      31: return
    Exception table:
       from    to  target type
           0    18    21   Class java/lang/Exception
}
