Compiled from "JtaIsolationDelegate.java"
class org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate$2$1 implements org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate$HibernateCallable<T> {
  final org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate$2 this$1;

  org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate$2$1(org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate$2);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #1                  // Field this$1:Lorg/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate$2;
       5: aload_0
       6: invokespecial #2                  // Method java/lang/Object."<init>":()V
       9: return

  public T call() throws org.hibernate.HibernateException;
    Code:
       0: aload_0
       1: getfield      #1                  // Field this$1:Lorg/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate$2;
       4: getfield      #3                  // Field org/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate$2.val$callable:Ljava/util/concurrent/Callable;
       7: invokeinterface #4,  1            // InterfaceMethod java/util/concurrent/Callable.call:()Ljava/lang/Object;
      12: areturn
      13: astore_1
      14: aload_1
      15: athrow
      16: astore_1
      17: new           #5                  // class org/hibernate/HibernateException
      20: dup
      21: aload_1
      22: invokespecial #7                  // Method org/hibernate/HibernateException."<init>":(Ljava/lang/Throwable;)V
      25: athrow
    Exception table:
       from    to  target type
           0    12    13   Class org/hibernate/HibernateException
           0    12    16   Class java/lang/Exception
}
