Compiled from "Try.scala"
public final class scala.util.Failure$$anonfun$recover$1 extends scala.runtime.AbstractFunction0<U> implements scala.Serializable {
  public static final long serialVersionUID;

  private final scala.util.Failure $outer;

  private final scala.PartialFunction rescueException$1;

  public final U apply();
    Code:
       0: aload_0
       1: getfield      #25                 // Field rescueException$1:Lscala/PartialFunction;
       4: aload_0
       5: getfield      #27                 // Field $outer:Lscala/util/Failure;
       8: invokevirtual #31                 // Method scala/util/Failure.exception:()Ljava/lang/Throwable;
      11: invokeinterface #36,  2           // InterfaceMethod scala/PartialFunction.apply:(Ljava/lang/Object;)Ljava/lang/Object;
      16: areturn

  public scala.util.Failure$$anonfun$recover$1(scala.util.Failure<T>);
    Code:
       0: aload_1
       1: ifnonnull     6
       4: aconst_null
       5: athrow
       6: aload_0
       7: aload_1
       8: putfield      #27                 // Field $outer:Lscala/util/Failure;
      11: aload_0
      12: aload_2
      13: putfield      #25                 // Field rescueException$1:Lscala/PartialFunction;
      16: aload_0
      17: invokespecial #43                 // Method scala/runtime/AbstractFunction0."<init>":()V
      20: return
}
