Compiled from "Functions.java"
final class net.jodah.failsafe.Functions$3 extends net.jodah.failsafe.Functions$AsyncCallableWrapper<T> {
  final java.util.concurrent.Callable val$callable;

  net.jodah.failsafe.Functions$3(java.util.concurrent.Callable);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #1                  // Field val$callable:Ljava/util/concurrent/Callable;
       5: aload_0
       6: invokespecial #2                  // Method net/jodah/failsafe/Functions$AsyncCallableWrapper."<init>":()V
       9: return

  public T call() throws java.lang.Exception;
    Code:
       0: aload_0
       1: getfield      #3                  // Field execution:Lnet/jodah/failsafe/AsyncExecution;
       4: invokevirtual #4                  // Method net/jodah/failsafe/AsyncExecution.before:()V
       7: aload_0
       8: getfield      #1                  // Field val$callable:Ljava/util/concurrent/Callable;
      11: invokeinterface #5,  1            // InterfaceMethod java/util/concurrent/Callable.call:()Ljava/lang/Object;
      16: astore_1
      17: aload_0
      18: getfield      #3                  // Field execution:Lnet/jodah/failsafe/AsyncExecution;
      21: aload_1
      22: aconst_null
      23: invokevirtual #6                  // Method net/jodah/failsafe/AsyncExecution.completeOrRetry:(Ljava/lang/Object;Ljava/lang/Throwable;)Z
      26: pop
      27: aload_1
      28: areturn
      29: astore_1
      30: aload_0
      31: getfield      #3                  // Field execution:Lnet/jodah/failsafe/AsyncExecution;
      34: aconst_null
      35: aload_1
      36: invokevirtual #6                  // Method net/jodah/failsafe/AsyncExecution.completeOrRetry:(Ljava/lang/Object;Ljava/lang/Throwable;)Z
      39: pop
      40: aconst_null
      41: areturn
    Exception table:
       from    to  target type
           0    28    29   Class java/lang/Throwable
}
