Compiled from "ShouldHaveRootCauseExactlyInstance.java"
public class org.assertj.core.error.ShouldHaveRootCauseExactlyInstance extends org.assertj.core.error.BasicErrorMessageFactory {
  public static org.assertj.core.error.ErrorMessageFactory shouldHaveRootCauseExactlyInstance(java.lang.Throwable, java.lang.Class<? extends java.lang.Throwable>);
    Code:
       0: aload_0
       1: invokestatic  #13                 // Method org/assertj/core/util/Throwables.getRootCause:(Ljava/lang/Throwable;)Ljava/lang/Throwable;
       4: ifnonnull     18
       7: new           #2                  // class org/assertj/core/error/ShouldHaveRootCauseExactlyInstance
      10: dup
      11: aload_1
      12: invokespecial #17                 // Method "<init>":(Ljava/lang/Class;)V
      15: goto          27
      18: new           #2                  // class org/assertj/core/error/ShouldHaveRootCauseExactlyInstance
      21: dup
      22: aload_0
      23: aload_1
      24: invokespecial #20                 // Method "<init>":(Ljava/lang/Throwable;Ljava/lang/Class;)V
      27: areturn

  private org.assertj.core.error.ShouldHaveRootCauseExactlyInstance(java.lang.Throwable, java.lang.Class<? extends java.lang.Throwable>);
    Code:
       0: aload_0
       1: ldc           #29                 // String %nExpecting a throwable with root cause being exactly an instance of:%n <%s>%nbut was an instance of:%n <%s>
       3: iconst_2
       4: anewarray     #31                 // class java/lang/Object
       7: dup
       8: iconst_0
       9: aload_2
      10: aastore
      11: dup
      12: iconst_1
      13: aload_1
      14: invokestatic  #13                 // Method org/assertj/core/util/Throwables.getRootCause:(Ljava/lang/Throwable;)Ljava/lang/Throwable;
      17: aastore
      18: invokespecial #34                 // Method org/assertj/core/error/BasicErrorMessageFactory."<init>":(Ljava/lang/String;[Ljava/lang/Object;)V
      21: return

  private org.assertj.core.error.ShouldHaveRootCauseExactlyInstance(java.lang.Class<? extends java.lang.Throwable>);
    Code:
       0: aload_0
       1: ldc           #38                 // String %nExpecting a throwable with root cause being exactly an instance of:%n <%s>%nbut current throwable has no cause.
       3: iconst_1
       4: anewarray     #31                 // class java/lang/Object
       7: dup
       8: iconst_0
       9: aload_1
      10: aastore
      11: invokespecial #34                 // Method org/assertj/core/error/BasicErrorMessageFactory."<init>":(Ljava/lang/String;[Ljava/lang/Object;)V
      14: return
}
