Compiled from "Exception.scala"
public final class scala.util.control.Exception$$anonfun$nonFatalCatcher$2 extends scala.runtime.AbstractFunction1<java.lang.Throwable, scala.runtime.Nothing$> implements scala.Serializable {
  public static final long serialVersionUID;

  public final scala.runtime.Nothing$ apply(java.lang.Throwable);
    Code:
       0: aload_1
       1: athrow

  public final java.lang.Object apply(java.lang.Object);
    Code:
       0: aload_0
       1: aload_1
       2: checkcast     #26                 // class java/lang/Throwable
       5: invokevirtual #28                 // Method apply:(Ljava/lang/Throwable;)Lscala/runtime/Nothing$;
       8: athrow

  public scala.util.control.Exception$$anonfun$nonFatalCatcher$2();
    Code:
       0: aload_0
       1: invokespecial #34                 // Method scala/runtime/AbstractFunction1."<init>":()V
       4: return
}
