Compiled from "Exception.scala"
public final class scala.util.control.Exception$$anonfun$throwableSubtypeToCatcher$1 extends scala.runtime.AbstractFunction1<Ex, java.lang.Object> implements scala.Serializable {
  public static final long serialVersionUID;

  private final scala.PartialFunction pf$1;

  public final boolean apply(Ex);
    Code:
       0: aload_0
       1: getfield      #23                 // Field pf$1:Lscala/PartialFunction;
       4: aload_1
       5: invokeinterface #29,  2           // InterfaceMethod scala/PartialFunction.isDefinedAt:(Ljava/lang/Object;)Z
      10: ireturn

  public final java.lang.Object apply(java.lang.Object);
    Code:
       0: aload_0
       1: aload_1
       2: checkcast     #36                 // class java/lang/Throwable
       5: invokevirtual #38                 // Method apply:(Ljava/lang/Throwable;)Z
       8: invokestatic  #44                 // Method scala/runtime/BoxesRunTime.boxToBoolean:(Z)Ljava/lang/Boolean;
      11: areturn

  public scala.util.control.Exception$$anonfun$throwableSubtypeToCatcher$1(scala.PartialFunction);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #23                 // Field pf$1:Lscala/PartialFunction;
       5: aload_0
       6: invokespecial #51                 // Method scala/runtime/AbstractFunction1."<init>":()V
       9: return
}
