Compiled from "Exception.scala"
public final class scala.util.control.Exception$$anonfun$unwrapping$1 extends scala.runtime.AbstractFunction1<java.lang.Throwable, scala.runtime.Nothing$> implements scala.Serializable {
  public static final long serialVersionUID;

  private final scala.collection.Seq exceptions$3;

  public final scala.runtime.Nothing$ apply(java.lang.Throwable);
    Code:
       0: getstatic     #25                 // Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
       3: aload_1
       4: aload_0
       5: getfield      #27                 // Field exceptions$3:Lscala/collection/Seq;
       8: invokevirtual #31                 // Method scala/util/control/Exception$.scala$util$control$Exception$$unwrap$1:(Ljava/lang/Throwable;Lscala/collection/Seq;)Ljava/lang/Throwable;
      11: athrow

  public final java.lang.Object apply(java.lang.Object);
    Code:
       0: aload_0
       1: aload_1
       2: checkcast     #38                 // class java/lang/Throwable
       5: invokevirtual #40                 // Method apply:(Ljava/lang/Throwable;)Lscala/runtime/Nothing$;
       8: athrow

  public scala.util.control.Exception$$anonfun$unwrapping$1(scala.collection.Seq);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #27                 // Field exceptions$3:Lscala/collection/Seq;
       5: aload_0
       6: invokespecial #47                 // Method scala/runtime/AbstractFunction1."<init>":()V
       9: return
}
