Compiled from "ClosureException.java"
public class groovy.lang.ClosureException extends java.lang.RuntimeException {
  private final groovy.lang.Closure closure;

  public groovy.lang.ClosureException(groovy.lang.Closure, java.lang.Throwable);
    Code:
       0: aload_0
       1: new           #11                 // class java/lang/StringBuilder
       4: dup
       5: invokespecial #14                 // Method java/lang/StringBuilder."<init>":()V
       8: ldc           #16                 // String Exception thrown by call to closure:
      10: invokevirtual #20                 // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
      13: aload_1
      14: invokevirtual #23                 // Method java/lang/StringBuilder.append:(Ljava/lang/Object;)Ljava/lang/StringBuilder;
      17: ldc           #25                 // String  reason:
      19: invokevirtual #20                 // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
      22: aload_2
      23: invokevirtual #23                 // Method java/lang/StringBuilder.append:(Ljava/lang/Object;)Ljava/lang/StringBuilder;
      26: invokevirtual #29                 // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
      29: aload_2
      30: invokespecial #32                 // Method java/lang/RuntimeException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
      33: aload_0
      34: aload_1
      35: putfield      #34                 // Field closure:Lgroovy/lang/Closure;
      38: return

  public groovy.lang.Closure getClosure();
    Code:
       0: aload_0
       1: getfield      #34                 // Field closure:Lgroovy/lang/Closure;
       4: areturn
}
